version: '3'

services:
  backend:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    volumes:
      - ../logs:/app/logs
    networks:
      - private
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.25.0
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro 
    volumes:
      - type: bind
        source: ../configs/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - private
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:15.3-alpine3.18
    volumes:
      - ../postgres/data:/var/lib/postgresql/data
    networks:
      - private
    restart: always
    env_file:
      - .env

networks:
  private:
